#!/usr/bin/env python3
"""Pixel profile builder for github.com/Trendorin.

    python3 build.py            build README, SUPPORT, assets and the local stand
    python3 build.py --open     ...then open the stand in a browser
    python3 build.py --offline  render the stand without the GitHub markdown API

Edit profile.toml, not the generated files. Empty values are skipped, so a
half-filled config never publishes placeholder links.

Standard library only (Python 3.11+). Optional: Pillow for the dithered avatar,
qrencode for crypto QR codes. All pixel text comes from the built-in 5x7 font,
so the SVGs carry no external fonts, scripts or third-party requests.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import html
import json
import random
import re
import shutil
import subprocess
import tomllib
import urllib.request
import webbrowser
from collections import defaultdict
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LOCAL = ROOT / "local"
MARK = "<!-- generated by build.py from profile.toml: edit the config, not this file -->"
GENERATED = "generated by build.py"

# ── Palette ──────────────────────────────────────────────────────────────────
# Every SVG ships in two variants and README switches them with <picture>.
THEMES = {
    "dark":  {"ink": "#ededed", "mid": "#8e8e8e", "dim": "#4a4a4a"},
    "light": {"ink": "#141414", "mid": "#6f6f6f", "dim": "#c4c4c4"},
}

# ── 5x7 bitmap font ("#" = pixel; narrow glyphs are allowed) ─────────────────
FONT = {
    "A": ".###. #...# #...# ##### #...# #...# #...#",
    "B": "####. #...# #...# ####. #...# #...# ####.",
    "C": ".###. #...# #.... #.... #.... #...# .###.",
    "D": "####. #...# #...# #...# #...# #...# ####.",
    "E": "##### #.... #.... ####. #.... #.... #####",
    "F": "##### #.... #.... ####. #.... #.... #....",
    "G": ".###. #...# #.... #.### #...# #...# .###.",
    "H": "#...# #...# #...# ##### #...# #...# #...#",
    "I": ".###. ..#.. ..#.. ..#.. ..#.. ..#.. .###.",
    "J": "..### ...#. ...#. ...#. ...#. #..#. .##..",
    "K": "#...# #..#. #.#.. ##... #.#.. #..#. #...#",
    "L": "#.... #.... #.... #.... #.... #.... #####",
    "M": "#...# ##.## #.#.# #...# #...# #...# #...#",
    "N": "#...# #...# ##..# #.#.# #..## #...# #...#",
    "O": ".###. #...# #...# #...# #...# #...# .###.",
    "P": "####. #...# #...# ####. #.... #.... #....",
    "Q": ".###. #...# #...# #...# #.#.# #..#. .##.#",
    "R": "####. #...# #...# ####. #.#.. #..#. #...#",
    "S": ".#### #.... #.... .###. ....# ....# ####.",
    "T": "##### ..#.. ..#.. ..#.. ..#.. ..#.. ..#..",
    "U": "#...# #...# #...# #...# #...# #...# .###.",
    "V": "#...# #...# #...# #...# #...# .#.#. ..#..",
    "W": "#...# #...# #...# #.#.# #.#.# ##.## #...#",
    "X": "#...# #...# .#.#. ..#.. .#.#. #...# #...#",
    "Y": "#...# #...# .#.#. ..#.. ..#.. ..#.. ..#..",
    "Z": "##### ....# ...#. ..#.. .#... #.... #####",
    "0": ".###. #...# #..## #.#.# ##..# #...# .###.",
    "1": "..#.. .##.. ..#.. ..#.. ..#.. ..#.. .###.",
    "2": ".###. #...# ....# ...#. ..#.. .#... #####",
    "3": "##### ...#. ..#.. ...#. ....# #...# .###.",
    "4": "...#. ..##. .#.#. #..#. ##### ...#. ...#.",
    "5": "##### #.... ####. ....# ....# #...# .###.",
    "6": "..##. .#... #.... ####. #...# #...# .###.",
    "7": "##### ....# ...#. ..#.. .#... .#... .#...",
    "8": ".###. #...# #...# .###. #...# #...# .###.",
    "9": ".###. #...# #...# .#### ....# ...#. .##..",
    " ": "... ... ... ... ... ... ...",
    ".": ". . . . . . #",
    ",": ".. .. .. .. .. .# #.",
    ":": ". . # . . # .",
    "!": "# # # # # . #",
    "?": ".###. #...# ....# ...#. ..#.. ..... ..#..",
    "'": "# # . . . . .",
    "-": "... ... ... ### ... ... ...",
    "_": "..... ..... ..... ..... ..... ..... #####",
    "+": "... ... .#. ### .#. ... ...",
    "=": "..... ..... ##### ..... ##### ..... .....",
    "/": "....# ....# ...#. ..#.. .#... #.... #....",
    "|": "# # # # # # #",
    "(": "..# .#. #.. #.. #.. .#. ..#",
    ")": "#.. .#. ..# ..# ..# .#. #..",
    "[": "### #.. #.. #.. #.. #.. ###",
    "]": "### ..# ..# ..# ..# ..# ###",
    "<": "...# ..#. .#.. #... .#.. ..#. ...#",
    ">": "#... .#.. ..#. ...# ..#. .#.. #...",
    "#": ".#.#. .#.#. ##### .#.#. ##### .#.#. .#.#.",
    "*": "..... ..#.. #.#.# .###. #.#.# ..#.. .....",
    "&": ".##.. #..#. #.#.. .#... #.#.# #..#. .##.#",
    "@": ".###. #...# #.### #.#.# #.### #.... .###.",
    "·": ". . . # . . .",
    # lowercase: x-height rows 2-6, descenders in rows 7-8
    "a": "..... ..... .###. ....# .#### #...# .#### ..... .....",
    "b": "#.... #.... ####. #...# #...# #...# ####. ..... .....",
    "c": "..... ..... .###. #.... #.... #.... .###. ..... .....",
    "d": "....# ....# .#### #...# #...# #...# .#### ..... .....",
    "e": "..... ..... .###. #...# ##### #.... .###. ..... .....",
    "f": "..## .#.. #### .#.. .#.. .#.. .#.. .... ....",
    "g": "..... ..... .#### #...# #...# #...# .#### ....# .###.",
    "h": "#.... #.... ####. #...# #...# #...# #...# ..... .....",
    "i": ".#. ... ##. .#. .#. .#. ### ... ...",
    "j": "...# .... ..## ...# ...# ...# ...# #..# .##.",
    "k": "#... #... #..# #.#. ##.. #.#. #..# .... ....",
    "l": "##. .#. .#. .#. .#. .#. ### ... ...",
    "m": "..... ..... ##.#. #.#.# #.#.# #.#.# #.#.# ..... .....",
    "n": "..... ..... ####. #...# #...# #...# #...# ..... .....",
    "o": "..... ..... .###. #...# #...# #...# .###. ..... .....",
    "p": "..... ..... ####. #...# #...# #...# ####. #.... #....",
    "q": "..... ..... .#### #...# #...# #...# .#### ....# ....#",
    "r": "..... ..... #.##. ##..# #.... #.... #.... ..... .....",
    "s": "..... ..... .#### #.... .###. ....# ####. ..... .....",
    "t": ".#.. .#.. #### .#.. .#.. .#.. ..## .... ....",
    "u": "..... ..... #...# #...# #...# #...# .#### ..... .....",
    "v": "..... ..... #...# #...# #...# .#.#. ..#.. ..... .....",
    "w": "..... ..... #...# #...# #.#.# #.#.# .#.#. ..... .....",
    "x": "..... ..... #...# .#.#. ..#.. .#.#. #...# ..... .....",
    "y": "..... ..... #...# #...# #...# #...# .#### ....# .###.",
    "z": "..... ..... ##### ...#. ..#.. .#... ##### ..... .....",
}
GLYPHS = {k: v.split() for k, v in FONT.items()}
LINE = 9  # rows a mixed-case line needs, descenders included
UNKNOWN: set[str] = set()

# 20x20 logos, pixelated from Simple Icons (CC0) and GitHub Octicons (MIT).
# Brand marks belong to their owners and are only used to label links to them.
LOGOS = {
    "github": (
        "........####........ .....##########..... ....############.... ...##############... "
        "..################.. .####..........####. .####..........####. ####............#### "
        "####............#### ####............#### ####............#### ####............#### "
        "####............#### #####..........##### .##.###.....#######. .###.###....#######. "
        "..##........######.. ...###......#####... ....####....####.... ......#......#......"
    ),
    "telegram": (
        ".......######....... .....##########..... ...##############... ..################.. "
        "..################.. .##################. .############..####. ##########....###### "
        "########......###### ######....#...###### ####....##....###### #########.....###### "
        "#########.....###### .#########....#####. .###########.######. ..################.. "
        "..################.. ...##############... .....##########..... .......######......."
    ),
    "boosty": (
        ".....######......... .....######......... .....#####.......... .....#####.......... "
        "....######.......... ....#####....##..... ....#####...#####... ...######...######.. "
        "...######...######.. ...#####...#######.. ...#####...#######.. ..######.....#####.. "
        "..#####.....######.. ..#######...######.. ..#######..######... ..#######.######.... "
        "..#############..... ..######.#####...... ...##########....... ....#######........."
    ),
    "tether": (
        ".................... ....############.... ...##############... ...##############... "
        "..###..........###.. ..###..........###.. .########..########. .########..########. "
        "#########..######### #########..######### .########..########. ..#######..#######.. "
        "...######..######... ....#####..#####.... .....####..####..... .......######....... "
        "........####........ .........##......... .................... ...................."
    ),
    "bitcoin": (
        ".......######....... .....##########..... ...##############... ..################.. "
        "..#######.########.. .######...#.#######. .#######.....######. ########..##..###### "
        "########.###..###### #######.......###### #######..##..####### #######..###..###### "
        "#####....###..###### .######.......#####. .######.#.#########. ..#######.########.. "
        "..################.. ...##############... .....##########..... .......######......."
    ),
    "monero": (
        ".......######....... .....##########..... ...##############... ..################.. "
        "..################.. .##################. .###.##########.###. ####..########..#### "
        "####...######...#### ####....####....#### ####.....##.....#### ####..#......#..#### "
        "####..##....##..#### ......###..###...... ......########...... ..################.. "
        "..################.. ...##############... .....##########..... .......######......."
    ),
    "ton": (
        ".......######....... .....##########..... ...##############... ..################.. "
        "..################.. .##################. .####..........####. #####.###..###.##### "
        "######.##..##.###### ######.##..##.###### #######.#..#.####### #######.#..#.####### "
        "########....######## .#######....#######. .########..########. ..################.. "
        "..################.. ...##############... .....##########..... .......######......."
    ),
    "mail": (
        ".................... .................... .##################. #################### "
        "#..................# ###..............### ####............#### #..###........###..# "
        "#....##......##....# #.....###...##.....# #.......####.......# #........##........# "
        "#..................# #..................# #..................# #..................# "
        "#################### .................... .................... ...................."
    ),
    "globe": (
        ".................... ......########...... .....##########..... ...###..#..#..###... "
        "...#...##..##...#... ..##...#....#...##.. .##...##....##...##. .##...##....##...##. "
        ".#....#......#....#. .##...##....##...##. .##################. .#....#......#....#. "
        ".##...##....##...##. .##...##....##...##. ..##...#....#...##.. ...#...##..##...#... "
        "...###..#..#..###... .....##########..... ......########...... ...................."
    ),
    "key": (
        "..........######.... .........###...##... ........##.......#.. .......##.........#. "
        ".......#..........## ......##.....##....# ......##.....##....# ......##...........# "
        "......##..........## ......##..........## .....##..........##. ....##..........##.. "
        "...##.....#######... ..##.....######..... .##....###.......... ##....##............ "
        "#...####............ #..####............. ##.#................ ####................"
    ),
    "card": (
        ".................... .................... .##################. #################### "
        "#..................# #..................# #..................# #################### "
        "##................## #..................# #..................# #..................# "
        "#...........####...# #..................# #..................# #..................# "
        "#################### .##################. .................... ...................."
    ),
    "heart": (
        ".................... .................... ....####....####.... ..###.###..###.###.. "
        ".##.....####.....##. .##......##......##. .#................#. .#................#. "
        ".#................#. .##..............##. ..#..............#.. ..##............##.. "
        "...##..........##... ....##........##.... .....##......##..... ......##....##...... "
        ".......######....... .........##......... .................... ...................."
    ),
}
ARROW = "..##### .....## ....#.# ...#..# ..#.... .#..... #......"  # 7x7 ↗

BAYER = [
    [0, 32, 8, 40, 2, 34, 10, 42], [48, 16, 56, 24, 50, 18, 58, 26],
    [12, 44, 4, 36, 14, 46, 6, 38], [60, 28, 52, 20, 62, 30, 54, 22],
    [3, 35, 11, 43, 1, 33, 9, 41], [51, 19, 59, 27, 49, 17, 57, 25],
    [15, 47, 7, 39, 13, 45, 5, 37], [63, 31, 55, 23, 61, 29, 53, 21],
]

# links.<key> → (card title, logo, href format, caption from value, warn when empty)
LINK_KINDS = {
    "telegram": ("TELEGRAM", "telegram", "{}", lambda v: "@" + v.rstrip("/").rsplit("/", 1)[-1], True),
    "email": ("EMAIL", "mail", "mailto:{}", lambda v: v, True),
    "website": ("WEBSITE", "globe", "{}", lambda v: re.sub(r"^https?://", "", v).rstrip("/"), False),
    "pgp": ("PGP KEY", "key", "{}", lambda v: re.sub(r"^https?://", "", v).rstrip("/"), False),
}
COIN_LOGOS = {"USDT": "tether", "TON": "ton", "GRAM": "ton", "BTC": "bitcoin", "XMR": "monero"}


def esc(s: str) -> str:
    return html.escape(str(s), quote=True)


def slug(s: str) -> str:
    s = s.lower().replace("+", "p").replace("#", "sharp")  # C++ → cpp, C# → csharp
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


# ── Pixel geometry ───────────────────────────────────────────────────────────
def text_layout(text: str, upper=True):
    """Per-character (x offset, pixels) and total width, in font units."""
    chars, x = [], 0
    for ch in text.upper() if upper else text:
        rows = GLYPHS.get(ch) or GLYPHS.get(ch.upper())
        if rows is None:
            UNKNOWN.add(ch)
            rows = GLYPHS["?"]
        pts = [(cx, cy) for cy, row in enumerate(rows) for cx, c in enumerate(row) if c == "#"]
        chars.append((x, pts))
        x += len(rows[0]) + 1
    return chars, max(x - 1, 0)


def text_pixels(text: str, upper=True):
    chars, width = text_layout(text, upper)
    return [(x0 + x, y) for x0, pts in chars for x, y in pts], width


def bitmap(rows: str):
    return [(x, y) for y, row in enumerate(rows.split()) for x, c in enumerate(row) if c == "#"]


def runs(pixels):
    """Merge unit pixels into horizontal runs (x, y, length)."""
    by_row = defaultdict(set)
    for x, y in pixels:
        by_row[y].add(x)
    out = []
    for y in sorted(by_row):
        xs = sorted(by_row[y])
        start = prev = xs[0]
        for x in xs[1:]:
            if x != prev + 1:
                out.append((start, y, prev - start + 1))
                start = x
            prev = x
        out.append((start, y, prev - start + 1))
    return out


def pixel_rects(pixels, s, ox=0, oy=0):
    return [(ox + x * s, oy + y * s, n * s, s) for x, y, n in runs(pixels)]


def d_rects(rects) -> str:
    return "".join(f"M{x} {y}h{w}v{h}h{-w}z" for x, y, w, h in rects)


def frame_rects(x, y, w, h, t=2, bottom=None):
    """Outline with notched (pixel-rounded) corners; optional thicker bottom edge."""
    b = bottom or t
    return [(x + t, y, w - 2 * t, t), (x + t, y + h - b, w - 2 * t, b),
            (x, y + t, t, h - t - b), (x + w - t, y + t, t, h - t - b)]


class Svg:
    def __init__(self, w, h, theme, label):
        self.w, self.h, self.theme, self.label = w, h, theme, label
        self.css, self.defs, self.body = [], [], []

    def rects(self, rects, cls, extra=""):
        if rects:
            self.body.append(f'<path class="{cls}"{extra} d="{d_rects(rects)}"/>')

    def __str__(self):
        css = ""
        if self.theme:
            t = THEMES[self.theme]
            css = f".i{{fill:{t['ink']}}}.m{{fill:{t['mid']}}}.d{{fill:{t['dim']}}}"
        if self.css:
            css += "".join(self.css) + "@media (prefers-reduced-motion:reduce){*{animation:none!important}}"
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{self.w}" height="{self.h}" '
            f'viewBox="0 0 {self.w} {self.h}" shape-rendering="crispEdges" role="img" '
            f'aria-label="{esc(self.label)}"><title>{esc(self.label)}</title>'
            + (f"<style>{css}</style>" if css else "")
            + (f"<defs>{''.join(self.defs)}</defs>" if self.defs else "")
            + "".join(self.body) + "</svg>\n"
        )


# ── Pieces ───────────────────────────────────────────────────────────────────
# Animations only ever hide things *while running*, so renderers that ignore
# CSS animation (or prefers-reduced-motion) show the finished frame.
ANIM = ("@keyframes h{from,to{opacity:0}}@keyframes b{50%{opacity:0}}"
        ".h{animation-name:h;animation-timing-function:steps(1,end)}")


# 12-row squared display font for the header wordmark. "*n" repeats a row.
BIG = {
    "A": ".########. ########## ##......##*3 ##########*2 ##......##*5",
    "B": "#########. ########## ##......##*3 #########.*2 ##......##*3 ########## #########.",
    "C": ".######### ########## ##........*8 ########## .#########",
    "D": "#########. ########## ##......##*8 ########## #########.",
    "E": "#########*2 ##.......*3 #######..*2 ##.......*3 #########*2",
    "F": "#########*2 ##.......*3 #######..*2 ##.......*5",
    "G": ".######### ########## ##........*3 ##...#####*2 ##......##*3 ########## .#########",
    "H": "##......##*5 ##########*2 ##......##*5",
    "I": "##*12",
    "J": ".......##*9 ##.....## ######### .#######.",
    "K": "##......## ##.....##. ##....##.. ##...##... ##..##.... #####.....*2 ##..##.... ##...##... "
         "##....##.. ##.....##. ##......##",
    "L": "##.......*10 #########*2",
    "M": "###......### ####....#### ##.##..##.## ##..####..## ##...##...## ##........##*7",
    "N": "###.....##*2 ####....##*2 ##.##...##*2 ##..##..##*2 ##...##.##*2 ##....####*2",
    "O": ".########. ########## ##......##*8 ########## .########.",
    "P": "#########. ########## ##......##*3 ########## #########. ##........*5",
    "Q": ".########. ########## ##......##*6 ##...##.## ##....#### ########## .#######.#",
    "R": "#########. ########## ##......##*3 ########## #########. ##...##... ##....##.. ##.....##. ##......##*2",
    "S": ".######### ########## ##........*3 #########. .######### ........##*3 ########## #########.",
    "T": "##########*2 ....##....*10",
    "U": "##......##*10 ########## .########.",
    "V": "##......##*8 .##....##. ..##..##.. ...####... ....##....",
    "W": "##........##*7 ##...##...## ##..####..## ##.##..##.## ####....#### ###......###",
    "X": "##......##*2 .##....##. ..##..##.. ...####... ....##....*2 ...####... ..##..##.. .##....##. ##......##*2",
    "Y": "##......##*2 .##....##. ..##..##.. ...####... ....##....*7",
    "Z": "##########*2 .......##. ......##.. .....##... ....##.... ...##..... ..##...... .##....... ##........ ##########*2",
    "0": ".########. ########## ##......##*3 ##..##..##*2 ##......##*3 ########## .########.",
    "1": "####.. ####.. ..##..*8 ######*2",
    "2": "#########. ########## ........##*3 .######### #########. ##........*3 ##########*2",
    "3": "#########. ########## ........##*3 ..########*2 ........##*3 ########## #########.",
    "4": "##......##*5 ##########*2 ........##*5",
    "5": "##########*2 ##........*3 #########. ########## ........##*3 ########## #########.",
    "6": ".######### ########## ##........*3 #########. ########## ##......##*3 ########## .########.",
    "7": "##########*2 ........##*10",
    "8": ".########. ########## ##......##*3 .########. ########## ##......##*3 ########## .########.",
    "9": ".########. ########## ##......##*3 ########## .######### ........##*3 ########## #########.",
    " ": ".....*12",
    "-": "......*5 ######*2 ......*5",
    ".": "..*10 ##*2",
}
BIG_GLYPHS = {k: [row for tok in v.split() for row in [tok.split("*")[0]] * int((tok.split("*") + ["1"])[1])]
              for k, v in BIG.items()}
assert all(len(g) == 12 and len({len(r) for r in g}) == 1 for g in BIG_GLYPHS.values()), "BIG glyphs must be 12 equal rows"

# The header is a dark "screen" in both GitHub themes; only its frame differs.
SCREEN = {"bg": "#0a0a0a", "hi": "#e4e4e4", "lo": "#8c8c8c", "shadow": "#1d1d1d", "noise": "#4e4e4e",
          "rule": "#333333", "sub": "#7a7a7a", "value": "#a6a6a6", "cursor": "#e4e4e4",
          "art": ("#3a3a3a", "#8c8c8c", "#e4e4e4"), "primary": "#5c5c5c",
          "dust": ("#1f1f1f", "#2f2f2f", "#4a4a4a"), "frame": {"dark": "#222222", "light": "#0a0a0a"}}


def big_layout(text, gap=2):
    """Per-character (x offset, width, pixels) and total width for the BIG font, in units."""
    chars, x = [], 0
    for ch in text.upper():
        rows = BIG_GLYPHS.get(ch)
        if rows is None:
            UNKNOWN.add(ch)
            rows = BIG_GLYPHS[" "]
        pts = [(cx, cy) for cy, row in enumerate(rows) for cx, c in enumerate(row) if c == "#"]
        chars.append((x, len(rows[0]), pts))
        x += len(rows[0]) + gap
    return chars, max(x - gap, 0)


def notched(x, y, w, h):
    """Rectangle with two-step pixel-rounded corners."""
    return [(x + 4, y, w - 8, h), (x + 2, y + 2, w - 4, h - 4), (x, y + 4, w, h - 8)]


def header_svg(title, subtitle, theme, W=764, H=248):  # 764 = two 380px cards + a space
    """Dark boot screen. The wordmark decodes out of pixel noise letter by letter,
    the subtitle types itself, then a glint sweeps the title every few seconds."""
    c = SCREEN
    rnd = random.Random(title + subtitle)  # deterministic: same config, same SVG
    chars, tw = big_layout(title)
    u = max(3, min(6, (W - 160) // max(tw, 1)))
    tx, ty, tww, th = (W - tw * u) // 2, 62, tw * u, 12 * u
    split = 7  # rows above are bright, rows below dim: a two-tone "chrome" cut
    uy = ty + th + 20
    sub, sw = text_layout("> " + subtitle)
    sx, sy = (W - (sw + 2 + 5) * 2) // 2, uy + 18

    # timeline, seconds
    frame_t, frames = 0.07, 5
    starts = [0.35 + i * 0.12 for i in range(len(chars))]
    settle = [t + frame_t * frames for t in starts]
    t_line = (settle[-1] if settle else 0.4) + 0.08
    t_sub = t_line + 0.5
    t_ready = t_sub + len(sub) * 0.03 + 0.05
    sweep = tww + 16 * u
    glint_steps = sweep // u

    svg = Svg(W, H, None, f"{title}: {subtitle}")
    svg.css.append(
        f".bg{{fill:{c['bg']}}}.fr{{fill:{c['frame'][theme]}}}.hi{{fill:{c['hi']}}}.lo{{fill:{c['lo']}}}"
        f".sh{{fill:{c['shadow']}}}.hd{{fill:{c['rule']}}}.sb{{fill:{c['sub']}}}"
        f".cu{{fill:{c['cursor']}}}.gl{{fill:#fff}}"
        + "".join(f".d{i}{{fill:{col}}}" for i, col in enumerate(c["dust"]))
        + f".nz{{fill:{c['noise']};opacity:0;animation:s {frame_t}s}}"
        "@keyframes h{from,to{opacity:0}}@keyframes s{from,to{opacity:1}}@keyframes b{50%{opacity:0}}"
        "@keyframes tw{50%{opacity:.12}}@keyframes ul{from{transform:scaleX(0)}}"
        f"@keyframes gl{{0%{{transform:translateX(0);animation-timing-function:steps({glint_steps},end)}}"
        f"14%,100%{{transform:translateX({sweep}px)}}}}"
        ".h{animation-name:h;animation-timing-function:steps(1,end)}"
        ".tw{animation:tw 5s steps(3,end) infinite}"
        f".ul{{transform-box:fill-box;transform-origin:center;animation:ul .45s steps(9,end) {t_line:.2f}s backwards}}"
        f".gb{{animation:gl 7s {t_ready + 0.4:.2f}s infinite}}"
    )

    # screen with a thin frame
    svg.rects(notched(0, 0, W, H), "fr")
    svg.rects(notched(2, 2, W - 4, H - 4), "bg")

    # star dust, kept away from the text blocks
    busy = [(tx - 28, ty - 18, tx + tww + 28, sy + 22)]
    for _ in range(22):
        size = rnd.choice((2, 2, 2, 4))
        x, y = rnd.randrange(14, W - 18, 2), rnd.randrange(12, H - 16, 2)
        if any(x0 <= x <= x1 and y0 <= y <= y1 for x0, y0, x1, y1 in busy):
            continue
        tone = rnd.choice((0, 0, 1, 1, 2))
        twinkle = rnd.random() < 0.35
        extra = f' style="animation-delay:-{rnd.uniform(0, 5):.2f}s"' if twinkle else ""
        svg.rects([(x, y, size, size)], f"d{tone}" + (" tw" if twinkle else ""), extra)

    # wordmark: noise frames, then shadow + two-tone letters, each slot settling in turn
    letters = []
    for (x0, w, pts), t0, t1 in zip(chars, starts, settle):
        ox = tx + x0 * u
        for k in range(frames):
            noise = [(x, y) for y in range(12) for x in range(w) if rnd.random() < 0.3]
            svg.rects(pixel_rects(noise, u, ox, ty), "nz", f' style="animation-delay:{t0 + k * frame_t:.2f}s"')
        dur = f' style="animation-duration:{t1:.2f}s"'
        svg.rects(pixel_rects(pts, u, ox + u, ty + u), "sh h", dur)
        svg.rects(pixel_rects([p for p in pts if p[1] < split], u, ox, ty), "hi h", dur)
        svg.rects(pixel_rects([p for p in pts if p[1] >= split], u, ox, ty), "lo h", dur)
        letters += pixel_rects(pts, u, ox, ty)

    # glint: a slanted pixel band clipped to the letters
    band = [(tx - 8 * u + ((11 - r) // 2) * u, ty + r * u, 2 * u, u) for r in range(12)]  # starts off the letters
    svg.defs.append(f'<clipPath id="t"><path d="{d_rects(letters)}"/></clipPath>')
    svg.body.append(f'<g clip-path="url(#t)"><path class="gl gb" d="{d_rects(band)}"/></g>')

    # underline that opens from the centre, with bright end caps
    svg.body.append(f'<g class="ul"><path class="hd" d="{d_rects([(tx, uy, tww, 2)])}"/>'
                    f'<path class="hi" d="{d_rects([(tx, uy - 1, 4, 4), (tx + tww - 4, uy - 1, 4, 4)])}"/></g>')

    # typed subtitle and cursor
    for i, (x0, pts) in enumerate(sub):
        if pts:
            svg.rects(pixel_rects([(x0 + x, y) for x, y in pts], 2, sx, sy), ("cu" if i == 0 else "sb") + " h",
                      f' style="animation-duration:{t_sub + i * 0.03:.2f}s"')
    svg.body.append(f'<rect class="cu" x="{sx + (sw + 2) * 2}" y="{sy}" width="10" height="14" '
                    f'style="animation:h {t_ready:.2f}s steps(1,end),b 1.1s steps(1,end) {t_ready:.2f}s infinite"/>')

    # slow CRT refresh band rolling down the screen
    svg.css.append(f"@keyframes rf{{0%{{transform:translateY(0);animation-timing-function:steps({H // 4},end)}}"
                   f"30%,100%{{transform:translateY({H}px)}}}}.rf{{animation:rf 9s {t_ready:.2f}s infinite}}")
    svg.body.append(f'<rect class="rf" x="2" y="-10" width="{W - 4}" height="10" fill="#fff" fill-opacity=".035"/>')

    # CRT scanlines over everything
    svg.defs.append(f'<pattern id="sl" width="4" height="3" patternUnits="userSpaceOnUse">'
                    f'<rect y="2" width="4" height="1" fill="#000" fill-opacity=".3"/></pattern>')
    svg.body.append(f'<path fill="url(#sl)" d="{d_rects(notched(2, 2, W - 4, H - 4))}"/>')
    return svg


def label_svg(text, theme, num=None, rule=72, s=2):
    """Section label between short dotted rules: ···· 01 / ABOUT ····.
    Kept narrow so phones show it at 1:1 instead of shrinking it."""
    parts = ([(f"{num:02d}", "m"), ("/", "d")] if num is not None else []) + [(text, "i" if num is not None else "d")]
    placed, x = [], 0
    for chunk, cls in parts:
        px, w = text_pixels(chunk)
        placed.append((x, px, cls))
        x += w + 4
    tw = (x - 4) * s
    gap, top = 18, 16
    W, H = 2 * (rule + gap) + tw, 7 * s + 24
    svg = Svg(W, H, theme, text)
    for xu, px, cls in placed:
        svg.rects(pixel_rects([(xu + a, b) for a, b in px], s, rule + gap, top), cls)
    dy = top + 3 * s
    dots = [(x, dy, 2, 2) for x in range(0, rule, 6)]
    dots += [(W - 2 - x, dy, 2, 2) for x in range(0, rule, 6)]
    svg.rects(dots, "d")
    return svg


def screen(svg, W, H, theme, extra_css=""):
    """Dark card body shared by every block: notched frame, background, colour classes."""
    c = SCREEN
    svg.css.append(
        f".bg{{fill:{c['bg']}}}.fr{{fill:{c['frame'][theme]}}}.pr{{fill:{c['primary']}}}.hi{{fill:{c['hi']}}}"
        f".lo{{fill:{c['lo']}}}.hd{{fill:{c['rule']}}}.sb{{fill:{c['sub']}}}.va{{fill:{c['value']}}}"
        + "".join(f".a{i + 1}{{fill:{col}}}" for i, col in enumerate(c["art"]))
        + "@keyframes h{from,to{opacity:0}}.h{animation-name:h;animation-timing-function:steps(1,end)}" + extra_css)
    svg.rects(notched(0, 0, W, H), "fr")
    svg.rects(notched(2, 2, W - 4, H - 4), "bg")


def scanlines(svg, W, H):
    svg.defs.append('<pattern id="sl" width="4" height="3" patternUnits="userSpaceOnUse">'
                    '<rect y="2" width="4" height="1" fill="#000" fill-opacity=".3"/></pattern>')
    svg.body.append(f'<path fill="url(#sl)" d="{d_rects(notched(2, 2, W - 4, H - 4))}"/>')


def wrap(text, width_px, s=2):
    """Greedy word wrap measured in pixel-font units."""
    lines, line = [], ""
    for word in text.split():
        trial = f"{line} {word}".strip()
        if line and text_layout(trial, upper=False)[1] * s > width_px:
            lines.append(line)
            line = word
        else:
            line = trial
    return lines + [line] if line else lines


def portrait_svg(grid, theme, label, W=300, H=320, gap=8):
    """Dithered portrait (4 tones) on the dark screen, scanned in top to bottom.
    `gap` keeps it off the readout when the two stack on phones."""
    n = len(grid)
    cell = max(1, min(W - 40, H - 40) // n)
    ox, oy = (W - n * cell) // 2, (H - n * cell) // 2
    svg = Svg(W, H + gap, None, label)
    screen(svg, W, H, theme)
    for band in range(0, n, 4):
        dur = f' style="animation-duration:{0.25 + band / 4 * 0.05:.2f}s"'
        for tone in (1, 2, 3):
            px = [(x, y) for y in range(band, min(band + 4, n)) for x in range(n) if grid[y][x] == tone]
            svg.rects(pixel_rects(px, cell, ox, oy), f"a{tone} h", dur)
    scanlines(svg, W, H)
    return svg


def spec_svg(user, host, rows, theme, W=460, H=None, s=2, gap=8):
    """neofetch-style readout: user@host, a rule, key/value rows and a gray ramp."""
    pad, pitch = 24, LINE * s + 4
    keyw = max(text_layout(k, upper=False)[1] for k, _ in rows) * s + 18
    lines = []
    for key, value in rows:
        for i, part in enumerate(wrap(value, W - 2 * pad - keyw, s)):
            lines.append((key if i == 0 else "", part))
    content = 62 + len(lines) * pitch + 16 + 12
    H = max(H or 0, content + pad)
    y0 = (H - content - pad) // 2  # centre the block when the card is taller than it needs
    svg = Svg(W, H + gap, None, f"{user}@{host}: " + "; ".join(f"{k} {v}" for k, v in rows))
    screen(svg, W, H, theme)

    x = pad
    for chunk, cls in ((user, "hi"), ("@", "sb"), (host, "hi")):
        px, w = text_pixels(chunk, upper=False)
        svg.rects(pixel_rects(px, s, x, pad + y0), f"{cls} h", ' style="animation-duration:.2s"')
        x += (w + 1) * s
    svg.rects([(pad, pad + y0 + 24, x - pad - s, 2)], "hd h", ' style="animation-duration:.3s"')
    for i, (key, value) in enumerate(lines):
        y = 62 + y0 + i * pitch
        dur = f' style="animation-duration:{0.4 + i * 0.09:.2f}s"'
        if key:
            svg.rects(pixel_rects(text_pixels(key, upper=False)[0], s, pad, y), "hi h", dur)
        svg.rects(pixel_rects(text_pixels(value, upper=False)[0], s, pad + keyw, y), "va h", dur)
    ramp = ("#1c1c1c", "#2e2e2e", "#474747", "#626262", "#7e7e7e", "#9c9c9c", "#c0c0c0", "#e4e4e4")
    dur = f' style="animation-duration:{0.5 + len(lines) * 0.09:.2f}s"'
    for k, col in enumerate(ramp):
        svg.body.append(f'<rect class="h" x="{pad + k * 26}" y="{62 + y0 + len(lines) * pitch + 16}" '
                        f'width="26" height="12" fill="{col}"{dur}/>')
    return svg


def card_svg(title, caption, logo, theme, primary=False, W=380, H=76, gap=8):
    """Link card: pixel logo, title, one-line caption, ↗. `gap` spaces wrapped rows."""
    s, tx = 2, 74
    room = W - tx - 40
    if text_layout(caption, upper=False)[1] * s > room:
        while caption and text_layout(caption + "..", upper=False)[1] * s > room:
            caption = caption[:-1]
        caption = caption.rstrip() + ".."
    svg = Svg(W, H + gap, None, f"{title}: {caption}")
    screen(svg, W, H, theme)
    if primary:  # inner ring marks the recommended option
        svg.rects(frame_rects(4, 4, W - 8, H - 8), "pr")
    svg.rects(pixel_rects(bitmap(LOGOS.get(logo, LOGOS["heart"])), 2, 18, (H - 40) // 2), "hi")
    svg.rects(pixel_rects(text_pixels(title, upper=False)[0], s, tx, 19), "hi")
    svg.rects(pixel_rects(text_pixels(caption, upper=False)[0], s, tx, 41), "va")
    svg.rects(pixel_rects(bitmap(ARROW), 2, W - 32, 19), "hi" if primary else "sb")
    return svg


def portrait_grid(path, cells=52, levels=4, refresh=True):
    """Dithered portrait grid, cached next to the picture as plain text (art/portrait.grid).
    CI reads the cache, so its output never depends on the runner's Pillow."""
    cache = path.with_suffix(".grid")
    grid = dither(path, cells, levels) if refresh and path.exists() else None
    if grid:
        text = "\n".join("".join(map(str, row)) for row in grid) + "\n"
        if not cache.exists() or cache.read_text() != text:
            cache.write_text(text)
        return grid
    if cache.exists():
        return [[int(c) for c in line] for line in cache.read_text().split()]
    return None


def dither(path, cells, levels):
    """Bayer-dither a picture into a cells×cells grid of tone indices (0 = darkest), or None."""
    try:
        from PIL import Image, ImageOps
    except ImportError:
        return None
    img = ImageOps.autocontrast(Image.open(path).convert("L"), cutoff=1).resize((cells, cells), Image.LANCZOS)
    px = img.load()
    grid = []
    for y in range(cells):
        row = []
        for x in range(cells):
            v = px[x, y] / 255 * (levels - 1)
            row.append(min(int(v) + (v - int(v) > (BAYER[y % 8][x % 8] + 0.5) / 64), levels - 1))
        grid.append(row)
    return grid


def qr_svg(data, u=4, quiet=4):
    """QR code via qrencode, always dark-on-white so every scanner reads it."""
    try:
        out = subprocess.run(["qrencode", "-t", "ASCII", "-m", "0", "-l", "M", "-o", "-", data],
                             capture_output=True, text=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError):
        return None
    rows = [line[::2] for line in out.splitlines() if line.strip()]
    px = [(x + quiet, y + quiet) for y, row in enumerate(rows) for x, c in enumerate(row) if c == "#"]
    size = (len(rows) + 2 * quiet) * u
    svg = Svg(size, size, None, "QR code")
    svg.body.append(f'<rect width="{size}" height="{size}" fill="#ffffff"/>')
    svg.body.append(f'<path fill="#111111" d="{d_rects(pixel_rects(px, u))}"/>')
    return svg


def logo_svg(text, s=3):
    """Inline pixel wordmark for the stand, drawn in currentColor."""
    px, w = text_pixels(text)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w * s} {7 * s}" width="{w * s}" height="{7 * s}" '
            f'shape-rendering="crispEdges" aria-hidden="true"><path fill="currentColor" d="{d_rects(pixel_rects(px, s))}"/></svg>')


# ── Markdown ─────────────────────────────────────────────────────────────────
def build(cfg, out: Path, live: dict, ci=False) -> list[str]:
    """Write README.md, SUPPORT.md, .github/* and assets/ into `out`. Returns TODO notes.
    Output depends only on the config, `live` and committed files under art/, so a CI
    rebuild is byte-identical unless a live value changed."""
    todo: list[str] = []
    p = cfg["profile"]
    login = p["login"]
    assets = out / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    written: set[str] = set()

    def svg2(name, make):
        for theme in THEMES:
            (assets / f"{name}-{theme}.svg").write_text(str(make(theme)))
            written.add(f"{name}-{theme}.svg")

    def pic(name, alt):
        return (f'<picture><source media="(prefers-color-scheme: dark)" srcset="assets/{name}-dark.svg">'
                f'<img src="assets/{name}-light.svg" alt="{esc(alt)}"></picture>')

    def card(name, title, caption, logo, url, primary=False):
        svg2(name, lambda t: card_svg(title, caption, logo, t, primary))
        return f'<a href="{esc(url)}">{pic(name, f"{title}: {caption}")}</a>'

    svg2("header", lambda t: header_svg(p["title"], p["tagline"], t))
    md = [MARK, "", '<div align="center">', "", pic("header", f"{p['title']}: {p['tagline']}"), ""]
    sections = []

    sections.append(("About", ["\n".join(line.strip() for line in para.strip().splitlines())
                               for para in p.get("about", "").strip().split("\n\n") if para.strip()]))

    spec = []
    for r in cfg.get("spec", []):
        value = r.get("value") or live.get(r.get("live", ""), "")
        if r.get("key") and value:
            spec.append((r["key"], value))
        elif r.get("live"):
            todo.append(f"spec {r.get('key')}: no value for live source {r['live']!r} yet (run online once)")
    if spec:
        user, host = login.lower(), "github"
        height = spec_svg(user, host, spec, "dark", gap=0).h  # portrait matches the readout's height
        alt = f"{user}@{host}: " + "; ".join(f"{k}: {v}" for k, v in spec)
        svg2("spec", lambda t: spec_svg(user, host, spec, t, H=height))
        block = pic("spec", alt)
        portrait = ROOT / p.get("portrait", "art/portrait.png")
        if grid := portrait_grid(portrait, refresh=not ci):
            svg2("portrait", lambda t: portrait_svg(grid, t, f"{p.get('name', login)}, dithered portrait", H=height))
            block = pic("portrait", "Dithered portrait") + " " + block
        else:
            todo.append(f"{portrait.relative_to(ROOT)}: no portrait or cached grid (needs Pillow once): skipped")
        sections.append(("System", [block]))

    if projects := [x for x in cfg.get("projects", []) if x.get("name") and x.get("url")]:
        sections.append(("Projects", [" ".join(
            card(f"project-{slug(x['name'])}", x["name"], x.get("description", ""), "github", x["url"])
            for x in projects)]))

    row = [card("link-github", "GITHUB", f"github.com/{login}", "github", f"https://github.com/{login}?tab=repositories")]
    for key, (title, logo, fmt, caption, loud) in LINK_KINDS.items():
        value = cfg.get("links", {}).get(key, "").strip()
        if value:
            row.append(card(f"link-{key}", title, caption(value), logo, fmt.format(value)))
        elif loud:
            todo.append(f"links.{key} is empty: the {title.title()} card is hidden")
    sections.append(("Contact", [" ".join(row)]))

    sup = cfg.get("support", {})
    s_links = [l for l in sup.get("links", []) if l.get("url")]
    todo += [f"support: {l['label']} has no url: hidden" for l in sup.get("links", []) if not l.get("url")]
    if sup.get("github_sponsors"):
        s_links.insert(0, {"label": "Sponsor", "logo": "github", "caption": "GitHub Sponsors",
                           "url": f"https://github.com/sponsors/{login}", "note": "GitHub Sponsors, monthly or one-time"})
    crypto = [c for c in sup.get("crypto", []) if c.get("address")]
    if not crypto:
        todo.append("support: no crypto addresses filled: crypto section hidden")

    support_md = out / "SUPPORT.md"
    if s_links or crypto:
        row = [card(f"support-{slug(l['label'])}", l["label"].upper(),
                    l.get("caption") or re.sub(r"^https?://(www\.)?", "", l["url"]).split("/")[0],
                    l.get("logo", "heart"), l["url"], primary=i == 0)
               for i, l in enumerate(s_links)]
        if crypto:
            row.append(card("support-crypto", "CRYPTO", " · ".join(c["coin"] for c in crypto),
                            COIN_LOGOS.get(crypto[0]["coin"].upper(), "heart"), "SUPPORT.md#crypto", primary=not s_links))
        sections.append(("Support", [sup.get("intro", "").strip(), " ".join(row),
                                     '<sub><a href="SUPPORT.md">all options and addresses → SUPPORT.md</a></sub>']))
        support_md.write_text(support_page(cfg, s_links, crypto, assets, svg2, pic, todo, written, ci))
    elif support_md.exists() and GENERATED in support_md.read_text():
        support_md.unlink()

    for i, (title, blocks) in enumerate(sections, 1):
        name = f"label-{slug(title)}"
        svg2(name, lambda t, i=i, title=title: label_svg(title, t, num=i))
        md += [pic(name, title), ""]
        for block in filter(None, blocks):
            md += [block, ""]

    snake = cfg.get("extras", {}).get("snake", False)
    workflow = out / ".github" / "workflows" / "snake.yml"
    if snake:
        raw = f"https://raw.githubusercontent.com/{login}/{login}/output"
        md += [f'<picture><source media="(prefers-color-scheme: dark)" srcset="{raw}/snake-dark.svg">'
               f'<img src="{raw}/snake-light.svg" alt="Contribution graph eaten by a pixel snake"></picture>', ""]
        workflow.parent.mkdir(parents=True, exist_ok=True)
        workflow.write_text(SNAKE_WORKFLOW)
    elif workflow.exists() and GENERATED in workflow.read_text():
        workflow.unlink()

    # refresh live values on a schedule while any spec row uses them
    live_wf = out / ".github" / "workflows" / "live.yml"
    if any(r.get("live") for r in cfg.get("spec", [])):
        live_wf.parent.mkdir(parents=True, exist_ok=True)
        live_wf.write_text(live_workflow(cfg.get("extras", {}).get("live_cron", "17 4 * * *")))
    elif live_wf.exists() and GENERATED in live_wf.read_text():
        live_wf.unlink()

    svg2("eof", lambda t: label_svg("EOF", t))
    md += [pic("eof", "EOF"), "", "</div>", ""]
    (out / "README.md").write_text("\n".join(md))
    write_funding(out, login, sup, s_links, crypto)
    for f in assets.iterdir():  # drop assets nothing references any more
        if f.name not in written:
            f.unlink()
    return todo


def support_page(cfg, s_links, crypto, assets, svg2, pic, todo, written, ci=False) -> str:
    svg2("support-header", lambda t: header_svg("SUPPORT", "Thank you for backing open source", t))
    md = [MARK, "", '<div align="center">', "", pic("support-header", "Support"), "", "</div>", "",
          "Everything I publish is free and open source. Support buys time to maintain it, "
          "write documentation and build new tools. Thank you for considering it.", ""]
    if s_links:
        md += ["## Platforms", ""]
        md += [f"- **[{l['label']}]({l['url']})**" + (f" · {l['note']}" if l.get("note") else "") for l in s_links]
        md += [""]
    if crypto:
        md += ["## Crypto", "",
               "> **Send only the listed coin on the listed network.** Crypto transfers are irreversible: "
               "after pasting, compare the first and last characters of the address.", ""]
        for c in crypto:
            md += [f"### {c['coin']}", "", f"Network: **{c.get('network', c['coin'])}**", "", "```text", c["address"], "```", ""]
            name = f"qr-{slug(c['coin'])}.svg"
            path = assets / name
            qr = None if ci and path.exists() else qr_svg(c["address"])
            if qr is not None:
                path.write_text(str(qr))
            elif path.exists():  # keep the committed code: CI runners have no qrencode
                todo.append("qrencode not found: reusing existing QR codes") if not ci else None
            else:
                todo.append("qrencode not found: QR codes skipped")
                continue
            written.add(name)
            width = qr.w if qr else re.search(r'width="(\d+)"', path.read_text())[1]
            md += ["<details><summary>QR code</summary>", "<br>", "",
                   f'<img src="assets/{name}" width="{width}" alt="QR code for the {esc(c["coin"])} address">', "",
                   "</details>", ""]
    md += ["## Other ways to help", "",
           "- Star the repositories you find useful",
           "- Report bugs, suggest features, send pull requests",
           "- Tell someone who might need these tools", ""]
    return "\n".join(md)


def write_funding(out, login, sup, s_links, crypto):
    """FUNDING.yml drives the Sponsor button on the repository page."""
    path = out / ".github" / "FUNDING.yml"
    lines = []
    if sup.get("github_sponsors"):
        lines.append(f"github: [{login}]")
    custom = [l["url"] for l in s_links if "github.com/sponsors/" not in l["url"]]
    if s_links or crypto:
        custom.append(f"https://github.com/{login}/{login}/blob/main/SUPPORT.md")
    if custom:
        lines.append("custom: [" + ", ".join(json.dumps(u) for u in custom[:4]) + "]")
    if lines:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"# {GENERATED} from profile.toml\n" + "\n".join(lines) + "\n")
    elif path.exists() and GENERATED in path.read_text():
        path.unlink()


SNAKE_WORKFLOW = f"""# {GENERATED} from profile.toml (extras.snake)
name: snake
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{{{ github.repository_owner }}}}
          outputs: |
            dist/snake-light.svg?color_snake=#141414&color_dots=#ebebeb,#c4c4c4,#8e8e8e,#5a5a5a,#262626
            dist/snake-dark.svg?color_snake=#ededed&color_dots=#161616,#3a3a3a,#646464,#9a9a9a,#d8d8d8
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
"""


# ── Live values ──────────────────────────────────────────────────────────────
# A spec row with `live = "<source>"` shows the newest value of that source.
# The last good value is committed in art/live.json, so builds work offline.
LIVE_FILE = ROOT / "art" / "live.json"


def arch_kernel():
    """Newest core/linux on Arch, formatted the way `uname -r` prints it: 7.2.6-arch2-1."""
    req = urllib.request.Request("https://archlinux.org/packages/core/x86_64/linux/json/",
                                 headers={"User-Agent": "profile-build (github.com/Trendorin)"})
    with urllib.request.urlopen(req, timeout=10) as r:
        pkg = json.load(r)
    version = re.sub(r"\.(arch\d+)$", r"-\1", pkg["pkgver"])  # 7.2.6.arch2 → 7.2.6-arch2
    return f"Linux {version}-{pkg['pkgrel']}"


LIVE_SOURCES = {"arch-kernel": arch_kernel}


def live_values(cfg, offline, todo):
    """Fetch every live source the config uses; fall back to the cached value on failure."""
    try:
        cache = json.loads(LIVE_FILE.read_text())
    except (OSError, ValueError):
        cache = {}
    for name in {r["live"] for r in cfg.get("spec", []) if r.get("live")}:
        if name not in LIVE_SOURCES:
            todo.append(f"unknown live source {name!r} (known: {', '.join(LIVE_SOURCES)})")
        elif not offline:
            try:
                cache[name] = LIVE_SOURCES[name]()
            except (OSError, ValueError, KeyError) as e:
                todo.append(f"live {name}: fetch failed ({type(e).__name__}), kept {cache.get(name, 'nothing')}")
    text = json.dumps(cache, indent=2, sort_keys=True) + "\n"
    if cache and (not LIVE_FILE.exists() or LIVE_FILE.read_text() != text):
        LIVE_FILE.write_text(text)
    return cache


def live_workflow(cron):
    """Scheduled refresh: one small JSON request per live source, a commit only when a value changed."""
    return f"""# {GENERATED} from profile.toml (spec rows with `live`, schedule: extras.live_cron)
name: live
on:
  schedule:
    - cron: "{cron}"
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: live
jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Rebuild with fresh live values
        run: python3 build.py --ci
      - name: Commit only if something changed
        run: |
          git add -A
          if git diff --cached --quiet; then echo "up to date"; exit 0; fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Kernel: $(python3 -c 'import json; print(json.load(open("art/live.json")).get("arch-kernel", "?"))')"
          git push
"""


# ── Local test stand ─────────────────────────────────────────────────────────
DEMO_LINKS = {"telegram": "https://t.me/example", "email": "hello@example.com"}


def demo_config(cfg):
    """Same config with sample values in every empty slot, for the stand only."""
    d = copy.deepcopy(cfg)
    links = d.setdefault("links", {})
    for key, value in DEMO_LINKS.items():
        links[key] = links.get(key) or value
    if not d.get("projects"):
        d["projects"] = [{"name": "example-tool", "url": "https://github.com/" + cfg["profile"]["login"],
                          "description": "demo entry: list real repositories in profile.toml"}]
    sup = d.setdefault("support", {})
    for l in sup.get("links", []):
        l["url"] = l.get("url") or f"https://example.com/{slug(l['label'])}"
    for c in sup.get("crypto", []):
        c["address"] = c.get("address") or f"DEMO-{c['coin']}-ADDRESS-DO-NOT-SEND"
    return d


def render_markdown(text: str, offline: bool, cache: dict):
    """GitHub's own renderer (cached by content, the API allows 60 calls/hour), else mini_markdown."""
    key = hashlib.sha256(text.encode()).hexdigest()
    if key in cache:
        return cache[key], "GitHub API"
    if not offline:
        req = urllib.request.Request(
            "https://api.github.com/markdown", data=json.dumps({"text": text, "mode": "markdown"}).encode(),
            headers={"Accept": "application/vnd.github+json", "User-Agent": "profile-build"})
        try:
            with urllib.request.urlopen(req, timeout=15) as r:
                cache[key] = r.read().decode()
                return cache[key], "GitHub API"
        except OSError:
            pass
    return mini_markdown(text), "offline renderer"


def mini_markdown(text: str) -> str:
    """Just enough Markdown for the generated files when the API is unreachable."""
    def inline(s):
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)

    out, para, lines, i = [], [], text.splitlines(), 0

    def flush():
        if para:
            out.append("<p>" + inline("\n".join(para)) + "</p>")
            para.clear()

    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            flush()
            j = i + 1
            while j < len(lines) and not lines[j].startswith("```"):
                j += 1
            out.append("<pre><code>" + esc("\n".join(lines[i + 1:j])) + "</code></pre>")
            i = j + 1
            continue
        if m := re.match(r"(#{1,6})\s+(.*)", line):
            flush()
            n = len(m[1])
            out.append(f'<h{n} id="{slug(m[2])}">{inline(m[2])}</h{n}>')
        elif line.startswith("- "):
            flush()
            items = []
            while i < len(lines) and lines[i].startswith("- "):
                items.append(f"<li>{inline(lines[i][2:])}</li>")
                i += 1
            out.append("<ul>" + "".join(items) + "</ul>")
            continue
        elif line.startswith("> "):
            flush()
            out.append(f"<blockquote><p>{inline(line[2:])}</p></blockquote>")
        elif not line.strip():
            flush()
        elif line.startswith(("<div", "</div", "<details", "</details", "<!--")):
            flush()
            out.append(line)
        else:
            para.append(line)
        i += 1
    flush()
    return "\n".join(out)


def build_avatars(cfg, todo):
    """Dithered avatars for GitHub settings → local/avatar/*.png and local/avatar.png."""
    src = ROOT / cfg["profile"].get("portrait", "art/portrait.png")
    try:
        from PIL import Image
    except ImportError:
        todo.append("Pillow not installed: avatar skipped (sudo pacman -S python-pillow)")
        return None
    if not src.exists():
        todo.append(f"{src.relative_to(ROOT)} missing: avatar skipped")
        return None
    outdir = LOCAL / "avatar"
    outdir.mkdir(parents=True, exist_ok=True)
    ramps = {2: [14, 236], 4: [14, 92, 164, 236]}

    def paint(grid, levels):
        img = Image.new("L", (len(grid), len(grid)))
        img.putdata([ramps[levels][v] for row in grid for v in row])
        return img

    variants = {
        "bayer-1bit": paint(dither(src, 115, 2), 2),
        "bayer-1bit-fine": paint(dither(src, 230, 2), 2),
        "bayer-4gray": paint(dither(src, 115, 4), 4),
        "floyd-1bit": Image.open(src).convert("L").resize((115, 115), Image.LANCZOS).convert("1")
                           .convert("L").point(lambda v: ramps[2][v > 127]),
    }
    for name, img in variants.items():
        img.resize((920, 920), Image.NEAREST).save(outdir / f"{name}.png", optimize=True)
    chosen = cfg["profile"].get("avatar_style", "bayer-4gray")
    if chosen not in variants:
        todo.append(f"profile.avatar_style {chosen!r} unknown: using bayer-4gray")
        chosen = "bayer-4gray"
    shutil.copy(outdir / f"{chosen}.png", LOCAL / "avatar.png")
    return list(variants), chosen


def build_stand(cfg, todo, avatars, chosen, offline):
    docs, engines, used = {}, set(), set()
    cache_file = LOCAL / ".markdown-cache.json"
    try:
        cache = json.loads(cache_file.read_text())
    except (OSError, ValueError):
        cache = {}
    for data, folder, prefix in (("real", ROOT, "../"), ("demo", LOCAL / "demo", "demo/")):
        for doc in ("README", "SUPPORT"):
            f = folder / f"{doc}.md"
            if not f.exists():
                docs[f"{data}:{doc}"] = None
                continue
            text = f.read_text()
            used.add(hashlib.sha256(text.encode()).hexdigest())
            body, engine = render_markdown(text, offline, cache)
            engines.add(engine)
            docs[f"{data}:{doc}"] = re.sub(r'(src|srcset)="(?:\./)?assets/', rf'\1="{prefix}assets/', body)
    cache_file.write_text(json.dumps({k: v for k, v in cache.items() if k in used}))
    engine = " + ".join(sorted(engines)) or "nothing to render"
    p = cfg["profile"]
    links = cfg.get("links", {})
    profile = {
        "name": p.get("name", ""), "login": p["login"], "bio": p.get("bio", ""),
        "links": [links[k] for k in ("website", "telegram", "email") if links.get(k)],
        "avatar": "avatar.png" if avatars else None, "avatars": avatars, "chosen": chosen,
    }
    page = (STAND.replace("__LOGO__", logo_svg("PROFILE STAND"))
            .replace("__DOCS__", json.dumps(docs).replace("</", "<\\/"))
            .replace("__PROFILE__", json.dumps(profile).replace("</", "<\\/"))
            .replace("__TODO__", json.dumps(sorted(set(todo))).replace("</", "<\\/"))
            .replace("__BUILD__", esc(f"{datetime.now():%Y-%m-%d %H:%M} · {engine}")))
    (LOCAL / "preview.html").write_text(page)
    return engine


STAND = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Profile Stand</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<!-- fonts load without blocking the first paint, so the stand also works offline -->
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Silkscreen&display=swap" rel="stylesheet" media="print" onload="this.media='all'">
<style>
:root{--bg:#e8e8e8;--panel:#f7f7f7;--ink:#121212;--mid:#666;--dot:#cdcdcd;
  --pix:"Silkscreen",ui-monospace,monospace;--mono:"JetBrains Mono",ui-monospace,SFMono-Regular,Menlo,monospace;color-scheme:light}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#0a0a0a;--panel:#121212;--ink:#ebebeb;--mid:#8a8a8a;--dot:#262626;color-scheme:dark}}
:root[data-theme="dark"]{--bg:#0a0a0a;--panel:#121212;--ink:#ebebeb;--mid:#8a8a8a;--dot:#262626;color-scheme:dark}
*{box-sizing:border-box}
html,body{margin:0}
body{background:var(--bg) conic-gradient(from 270deg at 2px 2px,var(--dot) 90deg,transparent 0) 0 0/24px 24px;
  color:var(--ink);font:14px/1.5 var(--mono);min-height:100vh}
.bar{position:sticky;top:0;z-index:5;display:flex;flex-wrap:wrap;align-items:center;gap:12px 18px;
  padding:14px 20px;background:var(--panel);border-bottom:2px solid var(--ink)}
.brand{display:flex;align-items:center;gap:14px;margin-right:auto;min-width:0}
.brand svg{display:block;color:var(--ink);height:21px;width:auto}
.brand span{font:11px var(--pix);color:var(--mid);text-transform:uppercase;white-space:nowrap}
.seg{display:flex;align-items:center}
.seg b{font:400 10px var(--pix);color:var(--mid);text-transform:uppercase;margin-right:8px}
.seg button{font:11px/1 var(--pix);text-transform:uppercase;color:var(--ink);background:var(--panel);
  border:2px solid var(--ink);padding:8px 10px;cursor:pointer;margin-left:-2px}
.seg button:first-of-type{margin-left:0}
.seg button[aria-pressed="true"]{background:var(--ink);color:var(--panel)}
.seg button:hover:not([aria-pressed="true"]){background:var(--dot)}
.seg button:focus-visible{outline:2px dashed var(--ink);outline-offset:3px;position:relative;z-index:1}
#stage{display:grid;gap:28px;padding:28px 20px;justify-items:center}
#stage.split{grid-template-columns:repeat(auto-fit,minmax(min(100%,720px),1fr));align-items:start;justify-items:stretch}
.screen{max-width:100%;border:2px solid var(--ink);background:var(--panel);box-shadow:6px 6px 0 var(--dot)}
.screen-bar{display:flex;justify-content:space-between;gap:12px;padding:6px 10px;background:var(--ink);color:var(--panel);
  font:10px var(--pix);text-transform:uppercase}
.gh{--font:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif;
  display:grid;grid-template-columns:260px minmax(0,1fr);gap:32px;width:1180px;max-width:100%;padding:32px;
  background:var(--gh-bg);color:var(--gh-fg);font:16px/1.5 var(--font)}
.gh[data-theme="dark"]{--gh-bg:#0d1117;--gh-fg:#f0f6fc;--gh-muted:#9198a1;--gh-border:#3d444d;--gh-link:#4493f8;--gh-code:rgba(101,108,118,.2);--gh-btn:#212830;--gh-row:#151b23}
.gh[data-theme="light"]{--gh-bg:#fff;--gh-fg:#1f2328;--gh-muted:#59636e;--gh-border:#d1d9e0;--gh-link:#0969da;--gh-code:rgba(129,139,152,.12);--gh-btn:#f6f8fa;--gh-row:#f6f8fa}
.gh.compact{grid-template-columns:minmax(0,1fr);width:960px}
.gh.compact .side{display:none}
.gh.mobile{width:390px;grid-template-columns:minmax(0,1fr);padding:16px;gap:16px}
.side .ava{display:block;width:100%;aspect-ratio:1;border-radius:50%;border:1px solid var(--gh-border);
  image-rendering:pixelated;background:var(--gh-row);object-fit:cover}
.side h1{margin:16px 0 0;font-size:24px;line-height:1.25;font-weight:600}
.side .login{margin:0 0 16px;font-size:20px;font-weight:300;color:var(--gh-muted)}
.side .follow{width:100%;padding:5px 16px;margin-bottom:16px;font:500 14px/20px var(--font);color:var(--gh-fg);
  background:var(--gh-btn);border:1px solid var(--gh-border);border-radius:6px}
.side .bio{margin:0 0 16px}
.side ul{list-style:none;margin:0;padding:0;font-size:14px}
.side li{margin:4px 0;overflow-wrap:anywhere}
.gh.mobile .side{display:grid;grid-template-columns:72px 1fr;column-gap:16px;align-items:center}
.gh.mobile .side .ava{grid-row:span 2}
.gh.mobile .side h1{margin:0;font-size:20px}
.gh.mobile .side .login{margin:0;font-size:16px}
.gh.mobile .side>:nth-child(n+4){grid-column:1/-1;margin-top:12px}
.readme{min-width:0;border:1px solid var(--gh-border);border-radius:6px}
.readme-head{padding:10px 16px;border-bottom:1px solid var(--gh-border);color:var(--gh-muted);font:12px var(--mono)}
.md{padding:24px;word-wrap:break-word}
.gh.mobile .md{padding:16px}
.md>:first-child{margin-top:0}
.md p,.md ul,.md pre,.md details,.md blockquote,.md table{margin:0 0 16px}
.md img{max-width:100%;box-sizing:content-box;vertical-align:middle}
.md a{color:var(--gh-link);text-decoration:none}
.md a:hover{text-decoration:underline}
.md h1,.md h2{padding-bottom:.3em;border-bottom:1px solid var(--gh-border)}
.md h1,.md h2,.md h3{margin:24px 0 16px;font-weight:600;line-height:1.25}
.md h2{font-size:1.5em}.md h3{font-size:1.25em}
.md .markdown-heading{position:relative}.md .anchor{display:none}
.md code{padding:.2em .4em;font:85% ui-monospace,SFMono-Regular,Menlo,monospace;background:var(--gh-code);border-radius:6px}
.md pre{padding:16px;overflow:auto;background:var(--gh-code);border-radius:6px;font-size:85%}
.md pre code{padding:0;background:none;font-size:100%}
.md blockquote{padding:0 1em;color:var(--gh-muted);border-left:.25em solid var(--gh-border)}
.md ul{padding-left:2em}
.md summary{cursor:pointer}
.md sub{font-size:75%}
.md .empty{color:var(--gh-muted);font-style:italic}
.panel{width:min(1180px,100%);margin:0 auto 40px;padding:0 20px;display:grid;gap:20px;grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr))}
.card{border:2px solid var(--ink);background:var(--panel);padding:16px 18px}
.card h2{margin:0 0 12px;font:12px var(--pix);text-transform:uppercase;letter-spacing:.04em}
.card ul{margin:0;padding:0;list-style:none}
.card li{padding:4px 0;border-top:1px dashed var(--dot)}
.card li:first-child{border-top:0}
.card li::before{content:"▸ ";color:var(--mid)}
.card .ok::before{content:"✓ "}
.avatars{display:flex;flex-wrap:wrap;gap:12px}
.avatars figure{margin:0;text-align:center;font:10px var(--pix);color:var(--mid);text-transform:uppercase}
.avatars img{display:block;width:96px;height:96px;border-radius:50%;image-rendering:pixelated;border:2px solid var(--dot);margin-bottom:6px}
.avatars .on img{border-color:var(--ink)}
.foot{text-align:center;padding:0 20px 32px;color:var(--mid);font:10px var(--pix);text-transform:uppercase}
@media (max-width:720px){.bar{gap:10px}.brand{flex-basis:100%}.brand span{display:none}.seg b{display:none}#stage{padding:16px 8px}}
</style>
</head>
<body>
<header class="bar">
  <div class="brand">__LOGO__<span>trendorin · github profile</span></div>
  <div class="seg" data-key="doc"><b>File</b><button data-v="README">README</button><button data-v="SUPPORT">Support</button></div>
  <div class="seg" data-key="theme"><b>Theme</b><button data-v="dark">Dark</button><button data-v="light">Light</button><button data-v="split">Split</button></div>
  <div class="seg" data-key="data"><b>Data</b><button data-v="real">Real</button><button data-v="demo">Demo</button></div>
  <div class="seg" data-key="width"><b>Width</b><button data-v="desktop">Desktop</button><button data-v="mobile">Mobile</button></div>
</header>
<main id="stage" aria-live="polite"></main>
<section class="panel">
  <div class="card"><h2>To do before publishing</h2><ul id="todo"></ul></div>
  <div class="card"><h2>Avatar variants</h2><div class="avatars" id="avatars"></div></div>
</section>
<p class="foot">build __BUILD__ · run python3 build.py to refresh</p>
<script>
const DOCS = __DOCS__;
const PROFILE = __PROFILE__;
const TODO = __TODO__;
const esc = s => String(s).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let state = {doc: "README", theme: "dark", data: "real", width: "desktop"};
try { Object.assign(state, JSON.parse(localStorage.getItem("profile-stand") || "{}")); } catch (e) {}
// Deep links like preview.html#theme=split&data=demo override the remembered view.
for (const [k, v] of new URLSearchParams(location.hash.slice(1))) if (k in state) state[k] = v;
const save = () => { try { localStorage.setItem("profile-stand", JSON.stringify(state)); } catch (e) {} };

document.querySelectorAll(".seg").forEach(seg => seg.addEventListener("click", e => {
  const b = e.target.closest("button");
  if (!b) return;
  state[seg.dataset.key] = b.dataset.v;
  save(); render();
}));

function sidebar() {
  const p = PROFILE;
  const ava = p.avatar ? `<img class="ava" src="${esc(p.avatar)}" alt="">` : `<div class="ava"></div>`;
  const links = p.links.map(l => `<li>${esc(l)}</li>`).join("");
  return `<aside class="side">${ava}<h1>${esc(p.name)}</h1><p class="login">${esc(p.login)}</p>
    <button class="follow" type="button" tabindex="-1">Follow</button>
    <p class="bio">${esc(p.bio)}</p>${links ? `<ul>${links}</ul>` : ""}</aside>`;
}

function screen(theme) {
  const html = DOCS[`${state.data}:${state.doc}`];
  const compact = state.theme === "split" || state.doc !== "README";
  const el = document.createElement("section");
  el.className = "screen";
  el.innerHTML = `<div class="screen-bar"><span>${theme} theme · ${state.width}</span><span>${state.doc}.md · ${state.data} data</span></div>
    <div class="gh ${state.width}${compact && state.width !== "mobile" ? " compact" : ""}" data-theme="${theme}">
      ${state.doc === "README" ? sidebar() : ""}
      <div class="readme"><div class="readme-head">${esc(PROFILE.login)} / ${state.doc}.md</div>
      <article class="md">${html || `<p class="empty">No ${state.doc}.md with ${state.data} data: fill support links or crypto in profile.toml, or switch to Demo.</p>`}</article></div>
    </div>`;
  // GitHub picks the <picture> source by its own theme; do the same per screen.
  el.querySelectorAll(".md picture").forEach(pic => {
    const img = pic.querySelector("img"), dark = pic.querySelector('source[media*="dark"]');
    if (theme === "dark" && img && dark) img.src = dark.getAttribute("srcset");
    pic.querySelectorAll("source").forEach(s => s.remove());
  });
  el.querySelectorAll(".md a[href]").forEach(a => {
    const href = a.getAttribute("href");
    const file = /(^|\/)(README|SUPPORT)\.md(#.*)?$/.exec(href);
    if (file) {
      a.addEventListener("click", e => { e.preventDefault(); state.doc = file[2]; save(); render(); scrollTo(0, 0); });
    } else if (!href.startsWith("#")) { a.target = "_blank"; a.rel = "noopener"; }
  });
  return el;
}

function render() {
  document.querySelectorAll(".seg").forEach(seg => seg.querySelectorAll("button").forEach(b =>
    b.setAttribute("aria-pressed", String(state[seg.dataset.key] === b.dataset.v))));
  const stage = document.getElementById("stage");
  stage.className = state.theme === "split" ? "split" : "";
  stage.replaceChildren(...(state.theme === "split" ? ["dark", "light"] : [state.theme]).map(screen));
}

document.getElementById("todo").innerHTML = TODO.length
  ? TODO.map(t => `<li>${esc(t)}</li>`).join("")
  : `<li class="ok">nothing left, ready to push</li>`;
document.getElementById("avatars").innerHTML = PROFILE.avatars.length
  ? PROFILE.avatars.map(n => `<figure class="${n === PROFILE.chosen ? "on" : ""}"><img src="avatar/${esc(n)}.png" alt="${esc(n)} avatar"><figcaption>${esc(n)}</figcaption></figure>`).join("")
  : `<p>No avatar source found.</p>`;
render();
</script>
</body>
</html>
"""


# Everything that belongs in the GitHub repository, nothing local.
PUBLISH = ["README.md", "SUPPORT.md", "LICENSE", "build.py", "profile.toml", ".gitignore", "art", "assets", ".github"]


def export(dest=ROOT / "upload"):
    """Fresh copy of the publishable files in upload/, for GitHub → Add file → Upload files."""
    shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir()
    for name in PUBLISH:
        src = ROOT / name
        if src.is_dir():
            shutil.copytree(src, dest / name, ignore=shutil.ignore_patterns("__pycache__"))
        elif src.exists():
            shutil.copy2(src, dest / name)
    return sum(1 for f in dest.rglob("*") if f.is_file())


def main():
    ap = argparse.ArgumentParser(description="Build the pixel GitHub profile from profile.toml.")
    ap.add_argument("--offline", action="store_true", help="render the stand without the GitHub markdown API")
    ap.add_argument("--open", action="store_true", help="open the stand in a browser")
    ap.add_argument("--ci", action="store_true", help="GitHub Actions: publishable files only, no local/ stand")
    args = ap.parse_args()

    with open(ROOT / "profile.toml", "rb") as f:
        cfg = tomllib.load(f)
    todo = []
    live = live_values(cfg, args.offline, todo)
    todo += build(cfg, ROOT, live, ci=args.ci)
    if args.ci:
        print("\n".join(["✓ README.md, assets/ (ci)"] + [f"  · {t}" for t in sorted(set(todo))]))
        return
    build(demo_config(cfg), LOCAL / "demo", live)
    avatars, chosen = build_avatars(cfg, todo) or ([], None)
    if UNKNOWN:
        todo.append("pixel font has no glyph for: " + " ".join(sorted(UNKNOWN)) + " (drawn as ?)")
    engine = build_stand(cfg, todo, avatars, chosen, args.offline)

    print(f"✓ README.md, assets/ ({len(list((ROOT / 'assets').iterdir()))} files)"
          + (", SUPPORT.md" if (ROOT / "SUPPORT.md").exists() else ""))
    print(f"✓ local/preview.html  (markdown: {engine})")
    print(f"✓ upload/  ({export()} files): drag everything inside into GitHub → Add file → Upload files")
    for note in sorted(set(todo)):
        print(f"  · {note}")
    if args.open:
        webbrowser.open((LOCAL / "preview.html").as_uri())


if __name__ == "__main__":
    main()
